src/furo/navigation.py
`@functools.lru_cache` was added in Python 3.8 which is beyond what Read the Docs currently supports
Didn't test this locally, made this change through GitHub directly. Might want to try building the project in Python 3.7?
Closes #5
=> Use functools.lru_cache with maxsize=None

src/furo/__init__.py, src/furo/theme/base.html
The hash is now only based on the file content.
Fix #38
Note: I tried to implement it as a jinja filter (a.k.a. `path | furo_asset_hash`) but I don't see an obvious way to do it, because Sphinx seems to initialise the template before Jinja so I don't know how to get from the extension to the environment without getting ugly.
=> Fix stability of resources hashes

src/furo/assets/styles/_scaffold.sass
As mentioned in https://github.com/pradyunsg/furo/issues/36#issuecomment-735026670, the document body's scrollbars should not be customized, as having customized/thin scrollbars here is a bad user experience. The custom styles are only meant for the sidebars and the code boxes in the page content.
40acea53f382be77a09e3123d2d54e008c665304
=> Fix scrollbar styles affecting document body

src/furo/assets/styles/components/_sidebar.sass
If a customized `html_sidebars` list is used and `scroll-start` is set before `search`, then scrolling down the sidebar will also scroll the searchbox's icon, as its position is set to absolute. By setting the position of the searchbox container to relative, the icon stays at its intended position while scrolling.
Example of the sidebar scrolled down by a bit and the icon having a vertical offset:
=> Fix icon position of sidebar-search-container

src/furo/theme/page.html
Hey! 
What do you think about adding a jinja2 block for announcement, to make overriding it easier?
TBH, what I really want is to add a permanent header on the top, which looks similar to announcement; having a block before `<div class="page">` would allow to add it without copy-pasting the whole template.
=> Allow setting announcement via templates

src/furo/theme/search.html
Search with furo theme is currently broken - see e.g. https://pradyunsg.me/furo/search/?q=css&check_keywords=yes&area=default
I think this is caused by a missing JS file (https://github.com/sphinx-doc/sphinx/blob/a18fee24f2b7f3507cfb02d56a48b107a78330e0/sphinx/themes/basic/search.html#L15), which is added in this PR.
=> Add language_data.js to search page

src/furo/__init__.py, src/furo/theme/base.html
Sphinx has the capability to include attributes for JavaScript files.
This commit changes the existing template string manipulation to
use the built-in support for JavaScript attributes instead.
=> Add defer to js_tag on Python side

docs/conf.py, docs/kitchen-sink/autodoc.rst, docs/kitchen-sink/demo_py/furo_demo_module.py, docs/kitchen-sink/index.md, src/furo/assets/styles/content/_api.sass
This is a patch for #137
It works on the site where I tested it, and doesn't appear to break the kitchen-sink demo.
---
Because `.viewcode-link` is already marked with `float: right` independently, don't assign that style redundantly when styling `[source]` links attached to function and class defintions.
Use `.viewcode-link` instead of `a.reference.internal` to ensure that the styling for `[source]` links is not accidentally applied to return type annotations which are also internal references.
=> Target [source] links more accurately in SASS

src/furo/theme/furo/page.html
Adjust the injection of separators between various components of a footer to only do so when needed. This is to handle various configuration states a user may set for `html_last_updated_fmt`, `html_show_copyright`, `html_show_sourcelink` or `html_show_sphinx`.
---
A capture of various configuration modes:
---
Note that with the provides changes, there are two minor tweaks to be considered before accepting this change.
**1)**
The period is purposely not injected at the end of a copyright statement. This provides flexibility for documentations which may not desire to inject a period after its statement (assuming there is no trailing content to append in the footer). For example:
**2)**
The vertical spacer was omitted in these changes to opt for using the existing period entries as the …
=> support various footer configurations

src/furo/theme/furo/search.html
The "search.html" template will generate a warning admonition about requiring JavaScript for search and automatically hiding the element when supported. While functional, if a client renders the page slowly, the warning notification may be visible to the user for a moment.
Instead of relying on JavaScript to suppress this warning, use a `noscript` tag to hide the warning for clients who do not support JavaScript. This also has the benefit of one less JavaScript call required by a client.
---
See also: https://github.com/sphinx-doc/sphinx/pull/9617
=> Use noscript for search js notification

src/furo/theme/furo/base.html, src/furo/theme/furo/sidebar/brand.html
Since Sphinx 4, it's possible to use URL in html_logo and html_favicon
options. It is not currently processed correctly and we end up with
something like "_static/https://example.com/logo.png" as image path.
Signed-off-by: Igor Ryzhov <iryzhov@nfware.com>
=> Fix URL in html_logo and html_favicon

README.md
Kitty is a butt-kicking terminal emulator and uses Sphinx + Furo theme for its documentation. Seems like a nice candidate for the Use By section.
=> Add kitty terminal emulator in the used by section

src/furo/theme/furo/base.html, src/furo/theme/furo/page.html, src/furo/theme/furo/sidebar/brand.html
The title element and sidebar branding name both use the `docstitle` configuration \[1\]\[2\] for its content; however, when using a `singlehtml` builder, this option is not available \[1\]\[3\]. In the case where this option is not available, this will lead to the sidebar name rendering a value "None" (unless `sidebar_hide_name` is explicitly configured to `True`) and some title values as "None". This commit adjusts the case where `docstitle` is not configured, by falling back onto the configured `project` value (for the sidebar) or the `title` value (for the title element).
\[1\]: https://www.sphinx-doc.org/en/master/templating.html?highlight=docstitle#docstitle
\[2\]: https://github.com/sphinx-doc/sphinx/blob/514fca7a407f03fae4c788178555a74256936655/sphinx/builders/html/__init__.py#L509 …
=> fallback to project name branding/title for singlehtml

.readthedocs.yaml, docs/conf.py
Hi @pradyunsg! I was experimenting with a new beta feature that we deployed yesterday in Read the Docs to allow setting a version for extra tools, for example, NodeJS (https://github.com/readthedocs/readthedocs-docker-images/issues/107)
This PR makes usage of that beta feature (`build.os` and `build.tools` configs from the `.readthedocs.yaml` file) to use Ubuntu 20.04 LTS and install NodeJS v14. Then, it runs `npx gulp build` from inside `conf.py` before building documentation with Sphinx.
I hope you find this useful! Let me know 😄
=> Build on Read the Docs

src/furo/__init__.py, src/furo/assets/styles/base/_index.sass, src/furo/assets/styles/base/_print.sass, src/furo/assets/styles/base/_theme.sass, src/furo/theme/furo/partials/_head_css_variables.html
The following improves the ability to print documentation themed with Furo. This includes hiding various elements (such as the mobile bar) that are not useful in printed media, as well as deals with color scheming issues for browsers who do not default to light scheme in a print media state.
---
These changes also resolve an issue (observed in Chrome/Edge; Firefox is fine) where the printing preview page would think there would be tens of thousands of pages to print:
=> Improve support for print media

src/furo/theme/furo/base.html
Fixes #410 
I tried adding this to the furo docs as well, but it doesn't work because the
Furo docs URLs are like https://pradyunsg.me/furo/recommendations/ instead of
https://pradyunsg.me/furo/recommendations.html.
=> Add rel="canonical" based on `html_baseurl` configuration

.pre-commit-config.yaml, src/furo/theme/furo/page.html
Running [Lighthouse](https://web.dev/measure/) on https://pillow.readthedocs.io/en/latest/ gives a good accessibility score with one suggestion:
For the edit icon:
> Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users. [Learn more](https://web.dev/link-name/?utm_source=lighthouse&utm_medium=lr).
Here's a suggestion, following https://kittygiraudel.com/2020/12/10/accessible-icon-links/
* Add `<span class="visually-hidden">Edit this page</span>` after the SVG, hidden but accessible
* Add `aria-hidden="true"` to the `<svg>` to remove it from the accessibility tree
* Addd `title="Edit this page` to the `<a>`, not strictly necessary but gives a tooltip
* I didn't bother with the IE …
=> Add accessible name to 'Edit this page' icon

src/furo/assets/styles/content/_tables.sass
With Markdown tables, one can control column alignment:
```markdown
| left | center | right |
| :--- | :----: | ----: |
| a    | b      | c     |
```
To enable this non-standard (in docutils) feature, MyST-Parser adds CSS classes to the `td`/`th`, which then require implementation by the HTML themes.
=> Support MyST table column alignment

src/furo/theme/furo/theme.conf
This was necessary to avoid the below message, and generate the edit button correctly pointing to a custom gitlab instance
```
preparing documents... WARNING: unsupported theme option 'source_edit_link' given
```
This fix (and especially this theme) works nicely for our doc site!
=> Add `source_edit_link` as supported theme configuration parameter

src/furo/assets/styles/base/_print.sass
While printing a Sphinx documentation page as PDF, I noticed a simple list (`<ul>`) was separated on two successive pages. I think simple CSS print rules could improve that kind of issues.
Inspiration source: https://www.alsacreations.com/astuce/lire/1160-une-feuille-de-styles-de-base-pour-le-media-print.html
Please note that I'm not fluent with the indented Sass syntax.
=> Print CSS: avoid page break in some relevant cases

src/furo/assets/styles/content/_api.sass
=> Fix left padding for `.sig-inline`

docs/kitchen-sink/generic.rst
Hi,
I think this is a typo - thought I'd open a PR to fix it if so.
Another option would be to write `user` instead of `read`/`reader` since the `GUI labels` section immediately above uses `user`, so it might be more consistent to use the same term in both places to refer to the user/reader (or alternatively, switch `user` for `reader` in the other section).
While I'm here, thanks for Furo, it's great!
=> Fix read/reader typo

src/furo/__init__.py
Replace `logging.warn` (deprecated in [Python 2.7, 2011](https://github.com/python/cpython/commit/04d5bc00a219860c69ea17eaa633d3ab9917409f)) with `logging.warning` (added in [Python 2.3, 2003](https://github.com/python/cpython/commit/6fa635df7aa88ae9fd8b41ae42743341316c90f7)).
* https://docs.python.org/3/library/logging.html#logging.Logger.warning
* https://github.com/python/cpython/issues/57444
=> Replace deprecated logging.warn with logging.warning

pyproject.toml
Apparently the Furo template is not affected by removal of the JS libraries.
Fixes: #556.
=> Support Sphinx 6.x

README.md
This reverts commit 25ddcf19a165584432f6fbe685a66d2104434927.
Unfortunatelly, we won't use Sphinx in GCC documentation for the future.
=> Revert "Document that GCC is using Furo! (#575)"

docs/kitchen-sink/generic.rst, src/furo/assets/styles/content/_code.sass
Inline code is currently only broken on "normal"
word break opportunities. Unfortunately, it depends
on the browser engine what "normal" word break
opportunities mean. This becomes very visible in
a typical example for a long inline string: a long
Unix-style path or an URL. Firefox considers a slash
("/") a word break opportunity, while Chrome doesn't.
To keep documentation readable we need to break long
inline code literals, otherwise they expand beyond
the viewport where they are of little use to the
reader.
Introducing "overflow-wrap: break-word" gives us
line-breaking in all browsers, even though the rendered
result will differ depending on the browser in question.
=> Break long inline code literals

docs/reference/code-blocks.md
Replace the old link (https://myst-parser.readthedocs.io/en/latest/using/intro.html#block-level-directives-with-myst-markdown) with the closest equivalent (https://myst-parser.readthedocs.io/en/latest/syntax/roles-and-directives.html).
Closes #593.
=> Fix a broken link in Markup Reference -> Code Blocks

src/furo/assets/styles/_scaffold.sass, src/furo/assets/styles/components/_footer.sass, src/furo/assets/styles/variables/_spacing.scss
This PR increases the size of some icons in order to improve accessibility, particularly for mobile devices. The larger sizes only consume a slightly larger horizontal width, while the vertical width is mainly unchanged due to padding/margin - which is great, because it only takes up previously empty space. I've included some before/after comparison images below.
I've found that on mobile the menu icons are harder to tap than they should be, and compared to honestly most other websites the proportions just look and feel unnatural. I've even had difficulty clicking the icons on desktop sometimes. These new sizes make the site feel more modern and easy to use.
<details open>
<summary><h2>Mobile</h2></summary>
- Before
- After
- Before
- After
</details>
<details> …
=> Increase icon sizes

src/furo/assets/styles/variables/_admonitions.scss
This PR increases the admonition title background opacity from 10% to 20%, resulting in a more vibrant mood and smoother contrast. If desired this value could even be raised to 25 or even 30 percent, although that may draw more attention than wanted. 
Currently, admonition title backgrounds are quite dark. When compared to the 100% opacity left border, there is a high contrast that looks out of place upon further inspection. The current opacity doesn't give enough overall contrast to the document as a whole, and therefore doesn't draw as much attention as you would expect from an admonition. Increasing the background opacity decreases the sharp contrast between the border and background, while increasing the overall contrast just enough to draw the eye to land on the admonition title, but …
=> Increase admonition title background opacity

docs/conf.py
Variable `templates_path` seems to be unused, since there is no `docs/_templates` subdir in this repo. This PR removes, the variable from the `docs/conf.py` file.
=> Remove unused `templates_path`

docs/conf.py, docs/customisation/footer.md
As reported in https://github.com/pradyunsg/furo/discussions/590, the example/test about using font-awesome is missing class `fa-brands`. This PR updates `docs/conf.py` and `docs/customisation/footer.md`.
Ref: https://github.com/pradyunsg/furo/discussions/400
=> Add missing class to Font Awesome examples

.pre-commit-config.yaml
The [`language_version` option](https://pre-commit.com/#overriding-language-version) tells pre-commit to run the hook using that specific version.
The current setting of 3.8 messes me up on my M1 because Python 3.8 does not work very well on Apple Silicon. 
Generally, it should not be necessary to set this value. Black determines what Python version to target with its `--target-version` option, which defaults to  `the project metadata in pyproject.toml`. Further, Black will error if it's run with an incompatible Python version.
=> Remove Python 3.8 constraint from Black pre-commit config

docs/customisation/index.md, docs/customisation/logo.md
The link `hide the name of the project in the sidebar` at the bottom of this page: https://pradyunsg.me/furo/customisation/logo/
is broken. It should point to: https://pradyunsg.me/furo/customisation/#sidebar-hide-name
Hopefully this PR fixes it (not sure, not super familiar with the markdown format for sphinx).
=> Fix broken link

src/furo/__init__.py
This patch respect the `HtmlFormatter` class set on `PygmentsBridge`, instead of hard-coding it into Furo. That way Furo can use the same Pygments formatter as the whole Sphinx machinery.
For the context, I encountered this issue while trying to implement a way for Pygments to render ANSI codes in documentation.
=> Use the reference `HtmlFormatter` class defined on `PygmentsBridge`

src/furo/__init__.py
``builder`` is already known to be an instance of ``StandaloneHTMLBuilder`` from the check on line 236.
A
=> Remove pointless assert

pyproject.toml
Python 3.7 is end of life [^1]
[^1]: https://devguide.python.org/versions/
A
=> Drop Python 3.7

src/furo/__init__.py
This is already checked in ``_builder_inited``, and also only the HTML builders emit ``html-page-context``.
A
=> Remove duplicate HTML builder check

src/furo/__init__.py
This provides a nicer error when failing, as ``ConfigError`` inherits from ``SphinxError``
=> Use ``sphinx.errors.ConfigError``

src/furo/__init__.py
I'm fairly sure that this was fixed by https://github.com/sphinx-doc/sphinx/pull/10079, included in Sphinx 4.4 -- this theme now requires Sphinx 6.
=> Simplify retrieval of ``pygments_dark_style`` value

docs/kitchen-sink/blocks.rst
Hi,
I think this is a typo, so thought I would open a PR to fix.
I found this since I often use different bits of Furo's docs as a reference for the different ways of doing things with Sphinx - thanks for writing them!
=> fix as/are typo in blocks.rst

src/furo/assets/styles/content/_footnotes.sass
Previously, only p elements were indented, leaving things like code blocks and block quotes unindented.
Fixes https://github.com/pradyunsg/furo/discussions/729
=> Indent all children of aside.footnote

src/furo/__init__.py
I had to add a workaround to ``_update_default`` in Sphinx 7.3.2.
There's no officially-supported method to change the default, but I believe the method here will work on pre and post Sphinx 7.3 -- in effect, if the user has not overriden the default via either ``conf.py`` or command-line overrides, set the new default value.
A
=> Patch ``app.config`` in a more resilient manner

src/furo/__init__.py
If a document has more than one TOC tree directive and no other headings on the page, an empty "Contents" section is rendered in the sidebar. Adjusting the hide-toc logic to check if all entries in the TOC tree are all local TOC tree entries.
=> Hide "Contents" on pages with multiple TOC trees

src/furo/__init__.py
Trying to run `nox -s lint` on the project, I discovered that `mypy` doesn't like one particular `return` call because the `type: ignore` comment is on the wrong line.
```text
src/furo/__init__.py:311: error: Returning Any from function declared to return "Style"  [no-any-return]
src/furo/__init__.py:312: error: Unused "type: ignore" comment  [unused-ignore]
```
=> Move a 'type: ignore' comment, for mypy

src/furo/assets/scripts/furo.js
Commit 38f17af endeavored to "Improve watcher for scroll issues", and appears to have succeeded in that goal.
But it also added a "debug printf"-style `console.log` call for the value of `headerTop`, whenever that watcher is run. Which means that Furo-powered sites all over the Internet are constantly spewing (almost exclusively) `headerTop: 0` onto the console, as users browse their pages.
=> Remove "debug printf" for headerTop value

src/furo/theme/furo/components/edit-this-page.html
This PR adds the rel="edit" attribute to the "Edit this page" edit link.
rel=edit lets a page indicate that the linked resource can be used to edit the page. It is defined at https://microformats.org/wiki/rel-edit. This can then be parsed by tools like the Universal Edit Button and custom bookmarklets to open the edit page corresponding with a website.
=> Add rel=edit attribute to "Edit this page" link/icon

src/furo/assets/scripts/furo.js
On iOS Safari, headerTop can sometimes be negative when scrolling and the comparison to 0 is no longer true, which removes the drop shadow and causes the flickering.
Remove the comparison with the header position to avoid DOM layout reads and fix the flickering by not comparing to exactly 0.
The flickering issue was discussed in #415. This was then linked to #681, but I couldn't reproduce the issue with the "Back to Top" button.
=> Fix flickering header drop shadow

src/furo/navigation.py, src/furo/theme/furo/page.html
* `<label><div>...` is invalid, so is `<button><div>...`
It seems like it can be simplified using `aria-label` on the referenced `<input>` and the `<buton>` itself, which avoids repetition as a bonus.
* Use `<span class="icon">` instead of `<i class="icon">` (the latter was popularized by font-awesome but is semantically questionable). The CSS just uses `.icon` anyways.
=> page.html: fix invalid HTML5

src/furo/theme/furo/base.html
Silences warnings from https://validator.w3.org: "trailing slash on void elements has no effect and interacts badly with unquoted attribute values."
=> base.html: fix trailing slash on void elements

src/furo/assets/styles/_scaffold.sass
The `::-webkit-scrollbar` selectors lead to 10k+ selector match attempts on browsers where they are redundant. Since these fallback rules were added 5 years ago, they are likely redundant by now.
The existing `article[role=main] *` performs much better and is all that's needed for modern browsers.
=> _scaffold.sass: remove old scrollbar selectors

README.md
I just noticed that Blender also uses furo for their documentation and thought it might be a nice candidate to add to the "used by" section since the software is very popular and highly regarded in the OSS community.
=> Add Blender to "used by" section
